-- COMANDO CREATE DATABASE
CREATE DATABASE AULA;

-- COMANDO PARA USAR/HABILIDAR BANCO DE DAOS 
USE AULA;

-- DROP - COMANDO PARA EXLCUIR O BANCO DE DADOS

DROP DATABASE AULA;


-- COMANDO PARA CRIAR UMA TABELA
CREATE table PRODUTOS(
IDPRODUTO int,
NOME varchar(45),
DESCRICAO TEXT,
PRECO DOUBLE
);

-- COMANDO PARA EXCLUIR UMA TABELA
DROP TABLE PRODUTOS

/*
TIPOS DE DADOS NO MYSQL

TIPO NUMÉRICO
INT - NÚMERO INTEIRO POSITIVO E NEGATIVO
FLOAT - NÚMERO REAL POSITIVO E NEGATIVO
DOUBLE - NÚMERO REAL POSITIVO E NEGATIVO
DECIMAL (I,D) - NÚMERO REAL POSITIVO E NEGATIVO
	EX. DECIMAL (10,2)
    NUMERIC - NÚMERO REAL
    
    TIPO TEXTO
    CHAR(T) - STRING DE UMA LINHA
    VARCHAR(T) - STRING VARIÁVEL DE UMA LINHA
    TEXT
    
    TIPO DATA E HORA
    DATE - SOMENTE DATA
    TIME - SOMENTE HORA
    DATETIME - DATA E HORA
    
    TIPO IMAGEM/SOM/VIDEO
    BLOB
    LONGBLOB
    
*/